/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as HomeLayoutImport } from './routes/_home/layout'
import { Route as HomeProfileImport } from './routes/_home/profile'
import { Route as HomeHomeImport } from './routes/_home/home'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any)

const HomeProfileRoute = HomeProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeHomeRoute = HomeHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => HomeLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_home/home': {
      id: '/_home/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeHomeImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_home/profile': {
      id: '/_home/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof HomeProfileImport
      parentRoute: typeof HomeLayoutImport
    }
  }
}

// Create and export the route tree

interface HomeLayoutRouteChildren {
  HomeHomeRoute: typeof HomeHomeRoute
  HomeProfileRoute: typeof HomeProfileRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeHomeRoute: HomeHomeRoute,
  HomeProfileRoute: HomeProfileRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof HomeLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/home': typeof HomeHomeRoute
  '/profile': typeof HomeProfileRoute
}

export interface FileRoutesByTo {
  '': typeof HomeLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/home': typeof HomeHomeRoute
  '/profile': typeof HomeProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_home': typeof HomeLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_home/home': typeof HomeHomeRoute
  '/_home/profile': typeof HomeProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/login' | '/home' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/login' | '/home' | '/profile'
  id: '__root__' | '/_home' | '/login' | '/_home/home' | '/_home/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_home",
        "/login"
      ]
    },
    "/_home": {
      "filePath": "_home/layout.tsx",
      "children": [
        "/_home/home",
        "/_home/profile"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_home/home": {
      "filePath": "_home/home.tsx",
      "parent": "/_home"
    },
    "/_home/profile": {
      "filePath": "_home/profile.tsx",
      "parent": "/_home"
    }
  }
}
ROUTE_MANIFEST_END */
